---
### Install etcd
- name: Install etcd
  yum: name=ectd state=present

### Render etcd conf
- name: Render etcd conf
  template: src=etcd.conf dest=/etc/etcd/etcd.conf mode=0644 owner=root group=root
  notify: Restart etcd

### Start etcd
- name: Start etcd
  service: name=etcd state=started

### Configure flanneld
- name: Configure flanneld
  template: src=flanneld.j2 dest=/etc/sysconfig/flanneld mode=0644 owner=root group=root

### Configure kubelet
- name: Configure kubelet
  template: src={{ items }}.j2 dest=/etc/kubernetes/{{ items }} mode=644 owner=root group=root backup=true 
  with_items:
    - apiserver.j2
    - config.j2
    - controller-manager.j2
    - scheduler.j2

