---
### Install etcd
- name: Install etcd
  yum: name=ectd state=presetn

### Render etcd conf
- name: Render etcd conf
  template: src=etcd.conf dest=/etc/etcd/etcd.conf mode=0644 owner=root group=root
  notify: Restart etcd

### Start etcd
- name: Start etcd
  service: name=etcd state=started
