---
### Add nginx repo 
- name: Add nginx repo
   yum_repository:
     name: nginx
     description: Nginx repo
     baseurl: http://nginx.org/packages/centos/7/$basearch/
     gpgcheck: no

### Install nginx
- name: Install nginx
  yum: name=nginx state=present

### Create web user and group
- name: Creat group {{ web_user }}
  group: name={{  web_user }} gid={{ web_id }} state=present

- name: Creat user {{ web_user }}
  user: name={{ web_user }} uid={{ web_id }} group={{ web_user }} state=present

### Remove nginx default.conf 
- name: Remove default.conf
  file: path=/etc/nginx/conf.d/default.conf state=absent

### Render user's nginx.conf
- name: Render conf
  template: src={{ item + '.j2' }} dest=/etc/nginx/{{ item }} mode=644 owner=root
  with_items:
    - nginx.conf

### Create web dir
- name: Create web dir
  file: path={{ web_root }} state=directory owner={{ web_user }} group={{ web_user }} mode=0755

### Render user's extend nginx.conf and restart
- name: Render nginx.ext.conf 
  template: src={{ item + '.j2' }} dest=/etc/nginx/conf.d/web.conf mode=644 owner=root backup=true
  with_items:
    - web.conf
  notify: Restart nginx

### Start nginx
- name: Start nginx
  service: name=nginx state=started 
